//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.GUI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EasySave.GUI.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        public static string SelectSourcePathFolder {
            get {
                return ResourceManager.GetString("SelectSourcePathFolder", resourceCulture);
            }
        }
        
        public static string SelectSourcePathFile {
            get {
                return ResourceManager.GetString("SelectSourcePathFile", resourceCulture);
            }
        }
        
        public static string SelectDestinationPath {
            get {
                return ResourceManager.GetString("SelectDestinationPath", resourceCulture);
            }
        }
        
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        public static string execute {
            get {
                return ResourceManager.GetString("execute", resourceCulture);
            }
        }
        
        public static string _break {
            get {
                return ResourceManager.GetString("break", resourceCulture);
            }
        }
        
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        public static string customizeSettings {
            get {
                return ResourceManager.GetString("customizeSettings", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string languageText {
            get {
                return ResourceManager.GetString("languageText", resourceCulture);
            }
        }
        
        public static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
        
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        public static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }
        
        public static string italian {
            get {
                return ResourceManager.GetString("italian", resourceCulture);
            }
        }
        
        public static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }
        
        public static string logFormat {
            get {
                return ResourceManager.GetString("logFormat", resourceCulture);
            }
        }
        
        public static string chooseBackupText {
            get {
                return ResourceManager.GetString("chooseBackupText", resourceCulture);
            }
        }
        
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        public static string createBackupJob {
            get {
                return ResourceManager.GetString("createBackupJob", resourceCulture);
            }
        }
        
        public static string createBackupText {
            get {
                return ResourceManager.GetString("createBackupText", resourceCulture);
            }
        }
        
        public static string jobDetails {
            get {
                return ResourceManager.GetString("jobDetails", resourceCulture);
            }
        }
        
        public static string jobName {
            get {
                return ResourceManager.GetString("jobName", resourceCulture);
            }
        }
        
        public static string giveName {
            get {
                return ResourceManager.GetString("giveName", resourceCulture);
            }
        }
        
        public static string enterJobName {
            get {
                return ResourceManager.GetString("enterJobName", resourceCulture);
            }
        }
        
        public static string backupTypeText {
            get {
                return ResourceManager.GetString("backupTypeText", resourceCulture);
            }
        }
        
        public static string backupType {
            get {
                return ResourceManager.GetString("backupType", resourceCulture);
            }
        }
        
        public static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        public static string sourceText {
            get {
                return ResourceManager.GetString("sourceText", resourceCulture);
            }
        }
        
        public static string selectSource {
            get {
                return ResourceManager.GetString("selectSource", resourceCulture);
            }
        }
        
        public static string selectTheSource {
            get {
                return ResourceManager.GetString("selectTheSource", resourceCulture);
            }
        }
        
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        public static string destinationText {
            get {
                return ResourceManager.GetString("destinationText", resourceCulture);
            }
        }
        
        public static string selectDestination {
            get {
                return ResourceManager.GetString("selectDestination", resourceCulture);
            }
        }
        
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        public static string executeAll {
            get {
                return ResourceManager.GetString("executeAll", resourceCulture);
            }
        }
        
        public static string noJobSelected {
            get {
                return ResourceManager.GetString("noJobSelected", resourceCulture);
            }
        }
        
        public static string selectJobText {
            get {
                return ResourceManager.GetString("selectJobText", resourceCulture);
            }
        }
        
        public static string noJobs {
            get {
                return ResourceManager.GetString("noJobs", resourceCulture);
            }
        }
        
        public static string addInstruction {
            get {
                return ResourceManager.GetString("addInstruction", resourceCulture);
            }
        }
    }
}
