<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>EasySave.GUI</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Ressources\svg\settings.svg" />
        <AvaloniaResource Include="Ressources\svg\Logo.svg" />
        <AvaloniaResource Include="Ressources\svg\settings.svg" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.11" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.11" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
        <PackageReference Include="Avalonia.Svg.Skia" Version="11.3.0" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\EasySave.Core\EasySave.Core.csproj" />
        <AvaloniaResource Include="Assets\**" />
        <AvaloniaResource Include="Ressources\**" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Ressources\Messages.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Messages.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Ressources\Messages.de-DE.resx">
            <DependentUpon>Messages.resx</DependentUpon>
        </EmbeddedResource>

        <EmbeddedResource Update="Ressources\Messages.fr-FR.resx">
            <DependentUpon>Messages.resx</DependentUpon>
        </EmbeddedResource>

        <EmbeddedResource Update="Ressources\Messages.es-ES.resx">
            <DependentUpon>Messages.resx</DependentUpon>
        </EmbeddedResource>

        <EmbeddedResource Update="Ressources\Messages.it-IT.resx">
            <DependentUpon>Messages.resx</DependentUpon>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Ressources\Messages.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Messages.resx</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
