<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <Nullable>enable</Nullable>
        <Version>1.1.0</Version>
        <RootNamespace>EasySave.CLI</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EasySave.Core\EasySave.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Ressources\Messages.fr-FR.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Language.fr-FR.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Ressources\Messages.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Language.en-US.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Ressources\Messages.es-ES.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Messages.es-ES.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Ressources\Messages.it-IT.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Messages.it-IT.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Ressources\Messages.de-DE.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Messages.de-DE.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Ressources\Messages.es-ES.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Messages.es-ES.resx</DependentUpon>
      </Compile>
      <Compile Update="Ressources\Messages.it-IT.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Messages.it-IT.resx</DependentUpon>
      </Compile>
      <Compile Update="Ressources\Messages.de-DE.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Messages.de-DE.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
