<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <Nullable>enable</Nullable>
        <Version>1.1.0</Version>
        <RootNamespace>EasySave.CLI</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EasySave.Core\EasySave.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Ressources\Messages.fr-FR.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Language.fr-FR.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Ressources\Messages.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Language.en-US.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

</Project>
