//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.CLI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_it_IT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_it_IT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.CLI.Resources.Messages.it-IT", typeof(Messages_it_IT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi un percorso (destinazione):.
        /// </summary>
        internal static string AddJobDestinationPath {
            get {
                return ResourceManager.GetString("AddJobDestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;aggiunta del lavoro..
        /// </summary>
        internal static string AddJobFailed {
            get {
                return ResourceManager.GetString("AddJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi un nome del lavoro:.
        /// </summary>
        internal static string AddJobName {
            get {
                return ResourceManager.GetString("AddJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definisci il tipo di backup che desideri:.
        /// </summary>
        internal static string AddJobSaveType {
            get {
                return ResourceManager.GetString("AddJobSaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi un percorso (origine):.
        /// </summary>
        internal static string AddJobSourcePath {
            get {
                return ResourceManager.GetString("AddJobSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavoro aggiunto con successo..
        /// </summary>
        internal static string AddJobSuccess {
            get {
                return ResourceManager.GetString("AddJobSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differenziale.
        /// </summary>
        internal static string AddJobTypeDifferential {
            get {
                return ResourceManager.GetString("AddJobTypeDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completo.
        /// </summary>
        internal static string AddJobTypeFull {
            get {
                return ResourceManager.GetString("AddJobTypeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiunto con successo al PATH!.
        /// </summary>
        internal static string AddToPathSucces {
            get {
                return ResourceManager.GetString("AddToPathSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Già presente nel Path!.
        /// </summary>
        internal static string AlreadyInPath {
            get {
                return ResourceManager.GetString("AlreadyInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglese.
        /// </summary>
        internal static string ChangeLanguageEnglish {
            get {
                return ResourceManager.GetString("ChangeLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spagnolo.
        /// </summary>
        internal static string ChangeLanguageEspañol {
            get {
                return ResourceManager.GetString("ChangeLanguageEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francese.
        /// </summary>
        internal static string ChangeLanguageFrench {
            get {
                return ResourceManager.GetString("ChangeLanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedesco.
        /// </summary>
        internal static string ChangeLanguageGerman {
            get {
                return ResourceManager.GetString("ChangeLanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input non valido. Impostazione predefinita su Inglese..
        /// </summary>
        internal static string ChangeLanguageInvalid {
            get {
                return ResourceManager.GetString("ChangeLanguageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string ChangeLanguageItalian {
            get {
                return ResourceManager.GetString("ChangeLanguageItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua cambiata con successo..
        /// </summary>
        internal static string ChangeLanguageSuccess {
            get {
                return ResourceManager.GetString("ChangeLanguageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia la lingua:.
        /// </summary>
        internal static string ChangeLanguageTitle {
            get {
                return ResourceManager.GetString("ChangeLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string ChangeLogFormatJson {
            get {
                return ResourceManager.GetString("ChangeLogFormatJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato di log cambiato con successo..
        /// </summary>
        internal static string ChangeLogFormatSuccess {
            get {
                return ResourceManager.GetString("ChangeLogFormatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia formato di log:.
        /// </summary>
        internal static string ChangeLogFormatTitle {
            get {
                return ResourceManager.GetString("ChangeLogFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string ChangeLogFormatXml {
            get {
                return ResourceManager.GetString("ChangeLogFormatXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi un lavoro.
        /// </summary>
        internal static string ConsoleMenuAddJob {
            get {
                return ResourceManager.GetString("ConsoleMenuAddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina lavoro.
        /// </summary>
        internal static string ConsoleMenuDeleteJob {
            get {
                return ResourceManager.GetString("ConsoleMenuDeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esegui tutti i lavori.
        /// </summary>
        internal static string ConsoleMenuExecuteAllJobs {
            get {
                return ResourceManager.GetString("ConsoleMenuExecuteAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esegui uno o più lavori.
        /// </summary>
        internal static string ConsoleMenuExecuteJob {
            get {
                return ResourceManager.GetString("ConsoleMenuExecuteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia lingua.
        /// </summary>
        internal static string ConsoleMenuLanguage {
            get {
                return ResourceManager.GetString("ConsoleMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia formato di log.
        /// </summary>
        internal static string ConsoleMenuLogFormat {
            get {
                return ResourceManager.GetString("ConsoleMenuLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli un&apos;opzione:.
        /// </summary>
        internal static string ConsoleMenuOption {
            get {
                return ResourceManager.GetString("ConsoleMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi EasySave al PATH.
        /// </summary>
        internal static string ConsoleMenuPath {
            get {
                return ResourceManager.GetString("ConsoleMenuPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esci.
        /// </summary>
        internal static string ConsoleMenuQuit {
            get {
                return ResourceManager.GetString("ConsoleMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza lavori salvati.
        /// </summary>
        internal static string ConsoleMenuViewJobs {
            get {
                return ResourceManager.GetString("ConsoleMenuViewJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rimozione del lavoro non riuscita..
        /// </summary>
        internal static string DeleteJobFailed {
            get {
                return ResourceManager.GetString("DeleteJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di lavoro non valido.
        /// </summary>
        internal static string DeleteJobInvalid {
            get {
                return ResourceManager.GetString("DeleteJobInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci il lavoro da rimuovere:.
        /// </summary>
        internal static string DeleteJobPrompt {
            get {
                return ResourceManager.GetString("DeleteJobPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavoro rimosso con successo.
        /// </summary>
        internal static string DeleteJobSuccess {
            get {
                return ResourceManager.GetString("DeleteJobSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorso di destinazione.
        /// </summary>
        internal static string DestinationPath {
            get {
                return ResourceManager.GetString("DestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutti i lavori sono stati completati con successo..
        /// </summary>
        internal static string ExecuteAllJobsSuccess {
            get {
                return ResourceManager.GetString("ExecuteAllJobsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esecuzione dei lavori non riuscita.
        /// </summary>
        internal static string ExecuteJobsFailed {
            get {
                return ResourceManager.GetString("ExecuteJobsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun lavoro disponibile..
        /// </summary>
        internal static string ExecuteJobsNoJobs {
            get {
                return ResourceManager.GetString("ExecuteJobsNoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun lavoro valido selezionato..
        /// </summary>
        internal static string ExecuteJobsNoValid {
            get {
                return ResourceManager.GetString("ExecuteJobsNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci i numeri dei lavori da eseguire (separati da virgole come 1;3 o 1-3):.
        /// </summary>
        internal static string ExecuteJobsPrompt {
            get {
                return ResourceManager.GetString("ExecuteJobsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavori completati con successo..
        /// </summary>
        internal static string ExecuteJobsSuccess {
            get {
                return ResourceManager.GetString("ExecuteJobsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai raggiunto il numero massimo di lavori. Per continuare, elimina un lavoro esistente. .
        /// </summary>
        internal static string MaxFileWarning {
            get {
                return ResourceManager.GetString("MaxFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Spazio = Seleziona/Deseleziona, Invio = Conferma).
        /// </summary>
        internal static string MultipleSelectionAdvice {
            get {
                return ResourceManager.GetString("MultipleSelectionAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;aggiunta al percorso.
        /// </summary>
        internal static string PathAddError {
            get {
                return ResourceManager.GetString("PathAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premi un tasto qualsiasi per continuare....
        /// </summary>
        internal static string PressKeyToContinue {
            get {
                return ResourceManager.GetString("PressKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riavvia il terminale affinché abbia effetto..
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup differenziale.
        /// </summary>
        internal static string SaveDifferentialType {
            get {
                return ResourceManager.GetString("SaveDifferentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completo.
        /// </summary>
        internal static string SaveFullType {
            get {
                return ResourceManager.GetString("SaveFullType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorso di origine.
        /// </summary>
        internal static string SourcePath {
            get {
                return ResourceManager.GetString("SourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grazie per aver utilizzato EasySave.
        /// </summary>
        internal static string ThankYouForUsing {
            get {
                return ResourceManager.GetString("ThankYouForUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun lavoro disponibile..
        /// </summary>
        internal static string ViewJobsNoJob {
            get {
                return ResourceManager.GetString("ViewJobsNoJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecco i lavori:.
        /// </summary>
        internal static string ViewJobsTitle {
            get {
                return ResourceManager.GetString("ViewJobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua già attiva..
        /// </summary>
        internal static string WarningLanguageActive {
            get {
                return ResourceManager.GetString("WarningLanguageActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato di log già attivo..
        /// </summary>
        internal static string WarningLogFormatActive {
            get {
                return ResourceManager.GetString("WarningLogFormatActive", resourceCulture);
            }
        }
    }
}
