//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.CLI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_es_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_es_ES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.CLI.Resources.Messages.es-ES", typeof(Messages_es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar una ruta (destino):.
        /// </summary>
        internal static string AddJobDestinationPath {
            get {
                return ResourceManager.GetString("AddJobDestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el trabajo..
        /// </summary>
        internal static string AddJobFailed {
            get {
                return ResourceManager.GetString("AddJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar un nombre de trabajo:.
        /// </summary>
        internal static string AddJobName {
            get {
                return ResourceManager.GetString("AddJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir el tipo de copia de seguridad que desea:.
        /// </summary>
        internal static string AddJobSaveType {
            get {
                return ResourceManager.GetString("AddJobSaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar una ruta (origen):.
        /// </summary>
        internal static string AddJobSourcePath {
            get {
                return ResourceManager.GetString("AddJobSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajo agregado con éxito..
        /// </summary>
        internal static string AddJobSuccess {
            get {
                return ResourceManager.GetString("AddJobSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diferencial.
        /// </summary>
        internal static string AddJobTypeDifferential {
            get {
                return ResourceManager.GetString("AddJobTypeDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completa.
        /// </summary>
        internal static string AddJobTypeFull {
            get {
                return ResourceManager.GetString("AddJobTypeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Agregado al PATH con éxito!.
        /// </summary>
        internal static string AddToPathSucces {
            get {
                return ResourceManager.GetString("AddToPathSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Ya está en el Path!.
        /// </summary>
        internal static string AlreadyInPath {
            get {
                return ResourceManager.GetString("AlreadyInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        internal static string ChangeLanguageEnglish {
            get {
                return ResourceManager.GetString("ChangeLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string ChangeLanguageEspañol {
            get {
                return ResourceManager.GetString("ChangeLanguageEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francés.
        /// </summary>
        internal static string ChangeLanguageFrench {
            get {
                return ResourceManager.GetString("ChangeLanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alemán.
        /// </summary>
        internal static string ChangeLanguageGerman {
            get {
                return ResourceManager.GetString("ChangeLanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada inválida. Cambiando a Inglés por defecto..
        /// </summary>
        internal static string ChangeLanguageInvalid {
            get {
                return ResourceManager.GetString("ChangeLanguageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string ChangeLanguageItalian {
            get {
                return ResourceManager.GetString("ChangeLanguageItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma cambiado con éxito..
        /// </summary>
        internal static string ChangeLanguageSuccess {
            get {
                return ResourceManager.GetString("ChangeLanguageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar el idioma:.
        /// </summary>
        internal static string ChangeLanguageTitle {
            get {
                return ResourceManager.GetString("ChangeLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string ChangeLogFormatJson {
            get {
                return ResourceManager.GetString("ChangeLogFormatJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de registro cambiado con éxito..
        /// </summary>
        internal static string ChangeLogFormatSuccess {
            get {
                return ResourceManager.GetString("ChangeLogFormatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar formato de registro:.
        /// </summary>
        internal static string ChangeLogFormatTitle {
            get {
                return ResourceManager.GetString("ChangeLogFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string ChangeLogFormatXml {
            get {
                return ResourceManager.GetString("ChangeLogFormatXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar un trabajo.
        /// </summary>
        internal static string ConsoleMenuAddJob {
            get {
                return ResourceManager.GetString("ConsoleMenuAddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar trabajo.
        /// </summary>
        internal static string ConsoleMenuDeleteJob {
            get {
                return ResourceManager.GetString("ConsoleMenuDeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar todos los trabajos.
        /// </summary>
        internal static string ConsoleMenuExecuteAllJobs {
            get {
                return ResourceManager.GetString("ConsoleMenuExecuteAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar uno o más trabajos.
        /// </summary>
        internal static string ConsoleMenuExecuteJob {
            get {
                return ResourceManager.GetString("ConsoleMenuExecuteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar idioma.
        /// </summary>
        internal static string ConsoleMenuLanguage {
            get {
                return ResourceManager.GetString("ConsoleMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar formato de registro.
        /// </summary>
        internal static string ConsoleMenuLogFormat {
            get {
                return ResourceManager.GetString("ConsoleMenuLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija una opción:.
        /// </summary>
        internal static string ConsoleMenuOption {
            get {
                return ResourceManager.GetString("ConsoleMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar EasySave al PATH.
        /// </summary>
        internal static string ConsoleMenuPath {
            get {
                return ResourceManager.GetString("ConsoleMenuPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string ConsoleMenuQuit {
            get {
                return ResourceManager.GetString("ConsoleMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver trabajos guardados.
        /// </summary>
        internal static string ConsoleMenuViewJobs {
            get {
                return ResourceManager.GetString("ConsoleMenuViewJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el trabajo..
        /// </summary>
        internal static string DeleteJobFailed {
            get {
                return ResourceManager.GetString("DeleteJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de trabajo inválido.
        /// </summary>
        internal static string DeleteJobInvalid {
            get {
                return ResourceManager.GetString("DeleteJobInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el trabajo a eliminar:.
        /// </summary>
        internal static string DeleteJobPrompt {
            get {
                return ResourceManager.GetString("DeleteJobPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajo eliminado con éxito.
        /// </summary>
        internal static string DeleteJobSuccess {
            get {
                return ResourceManager.GetString("DeleteJobSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de destino.
        /// </summary>
        internal static string DestinationPath {
            get {
                return ResourceManager.GetString("DestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los trabajos se han completado con éxito..
        /// </summary>
        internal static string ExecuteAllJobsSuccess {
            get {
                return ResourceManager.GetString("ExecuteAllJobsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la ejecución de trabajos.
        /// </summary>
        internal static string ExecuteJobsFailed {
            get {
                return ResourceManager.GetString("ExecuteJobsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay trabajos disponibles..
        /// </summary>
        internal static string ExecuteJobsNoJobs {
            get {
                return ResourceManager.GetString("ExecuteJobsNoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se seleccionaron trabajos válidos..
        /// </summary>
        internal static string ExecuteJobsNoValid {
            get {
                return ResourceManager.GetString("ExecuteJobsNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese los números de los trabajos a ejecutar (separados por comas como 1;3 o 1-3):.
        /// </summary>
        internal static string ExecuteJobsPrompt {
            get {
                return ResourceManager.GetString("ExecuteJobsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajos completados con éxito..
        /// </summary>
        internal static string ExecuteJobsSuccess {
            get {
                return ResourceManager.GetString("ExecuteJobsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha alcanzado el número máximo de trabajos. Para continuar, elimine un trabajo existente. .
        /// </summary>
        internal static string MaxFileWarning {
            get {
                return ResourceManager.GetString("MaxFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Espacio = Marcar/Desmarcar, Enter = Confirmar).
        /// </summary>
        internal static string MultipleSelectionAdvice {
            get {
                return ResourceManager.GetString("MultipleSelectionAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar al path.
        /// </summary>
        internal static string PathAddError {
            get {
                return ResourceManager.GetString("PathAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presione cualquier tecla para continuar....
        /// </summary>
        internal static string PressKeyToContinue {
            get {
                return ResourceManager.GetString("PressKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinicie su terminal para que esto tenga efecto..
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia de seguridad diferencial.
        /// </summary>
        internal static string SaveDifferentialType {
            get {
                return ResourceManager.GetString("SaveDifferentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia de seguridad completa.
        /// </summary>
        internal static string SaveFullType {
            get {
                return ResourceManager.GetString("SaveFullType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de origen.
        /// </summary>
        internal static string SourcePath {
            get {
                return ResourceManager.GetString("SourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por usar EasySave.
        /// </summary>
        internal static string ThankYouForUsing {
            get {
                return ResourceManager.GetString("ThankYouForUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay trabajos disponibles..
        /// </summary>
        internal static string ViewJobsNoJob {
            get {
                return ResourceManager.GetString("ViewJobsNoJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquí están los trabajos:.
        /// </summary>
        internal static string ViewJobsTitle {
            get {
                return ResourceManager.GetString("ViewJobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma ya activo..
        /// </summary>
        internal static string WarningLanguageActive {
            get {
                return ResourceManager.GetString("WarningLanguageActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de registro ya activo..
        /// </summary>
        internal static string WarningLogFormatActive {
            get {
                return ResourceManager.GetString("WarningLogFormatActive", resourceCulture);
            }
        }
    }
}
