//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.CLI.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.CLI.Ressources.Messages.de-DE", typeof(Messages_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad hinzufügen (Ziel):.
        /// </summary>
        internal static string AddJobDestinationPath {
            get {
                return ResourceManager.GetString("AddJobDestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen des Auftrags fehlgeschlagen..
        /// </summary>
        internal static string AddJobFailed {
            get {
                return ResourceManager.GetString("AddJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftragsnamen hinzufügen:.
        /// </summary>
        internal static string AddJobName {
            get {
                return ResourceManager.GetString("AddJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definieren Sie den gewünschten Sicherungstyp:.
        /// </summary>
        internal static string AddJobSaveType {
            get {
                return ResourceManager.GetString("AddJobSaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad hinzufügen (Quelle):.
        /// </summary>
        internal static string AddJobSourcePath {
            get {
                return ResourceManager.GetString("AddJobSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftrag erfolgreich hinzugefügt..
        /// </summary>
        internal static string AddJobSuccess {
            get {
                return ResourceManager.GetString("AddJobSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differenziell.
        /// </summary>
        internal static string AddJobTypeDifferential {
            get {
                return ResourceManager.GetString("AddJobTypeDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vollständig.
        /// </summary>
        internal static string AddJobTypeFull {
            get {
                return ResourceManager.GetString("AddJobTypeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich zu PATH hinzugefügt!.
        /// </summary>
        internal static string AddToPathSucces {
            get {
                return ResourceManager.GetString("AddToPathSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereits im Path!.
        /// </summary>
        internal static string AlreadyInPath {
            get {
                return ResourceManager.GetString("AlreadyInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisch.
        /// </summary>
        internal static string ChangeLanguageEnglish {
            get {
                return ResourceManager.GetString("ChangeLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanisch.
        /// </summary>
        internal static string ChangeLanguageEspañol {
            get {
                return ResourceManager.GetString("ChangeLanguageEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Französisch.
        /// </summary>
        internal static string ChangeLanguageFrench {
            get {
                return ResourceManager.GetString("ChangeLanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string ChangeLanguageGerman {
            get {
                return ResourceManager.GetString("ChangeLanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Eingabe. Standardmäßig auf Englisch gesetzt..
        /// </summary>
        internal static string ChangeLanguageInvalid {
            get {
                return ResourceManager.GetString("ChangeLanguageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italienisch.
        /// </summary>
        internal static string ChangeLanguageItalian {
            get {
                return ResourceManager.GetString("ChangeLanguageItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache erfolgreich geändert..
        /// </summary>
        internal static string ChangeLanguageSuccess {
            get {
                return ResourceManager.GetString("ChangeLanguageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache ändern:.
        /// </summary>
        internal static string ChangeLanguageTitle {
            get {
                return ResourceManager.GetString("ChangeLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string ChangeLogFormatJson {
            get {
                return ResourceManager.GetString("ChangeLogFormatJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokollformat erfolgreich geändert..
        /// </summary>
        internal static string ChangeLogFormatSuccess {
            get {
                return ResourceManager.GetString("ChangeLogFormatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokollformat ändern:.
        /// </summary>
        internal static string ChangeLogFormatTitle {
            get {
                return ResourceManager.GetString("ChangeLogFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string ChangeLogFormatXml {
            get {
                return ResourceManager.GetString("ChangeLogFormatXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftrag hinzufügen.
        /// </summary>
        internal static string ConsoleMenuAddJob {
            get {
                return ResourceManager.GetString("ConsoleMenuAddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftrag löschen.
        /// </summary>
        internal static string ConsoleMenuDeleteJob {
            get {
                return ResourceManager.GetString("ConsoleMenuDeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Aufträge ausführen.
        /// </summary>
        internal static string ConsoleMenuExecuteAllJobs {
            get {
                return ResourceManager.GetString("ConsoleMenuExecuteAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einen oder mehrere Aufträge ausführen.
        /// </summary>
        internal static string ConsoleMenuExecuteJob {
            get {
                return ResourceManager.GetString("ConsoleMenuExecuteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache ändern.
        /// </summary>
        internal static string ConsoleMenuLanguage {
            get {
                return ResourceManager.GetString("ConsoleMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokollformat ändern.
        /// </summary>
        internal static string ConsoleMenuLogFormat {
            get {
                return ResourceManager.GetString("ConsoleMenuLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie eine Option:.
        /// </summary>
        internal static string ConsoleMenuOption {
            get {
                return ResourceManager.GetString("ConsoleMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasySave zu PATH hinzufügen.
        /// </summary>
        internal static string ConsoleMenuPath {
            get {
                return ResourceManager.GetString("ConsoleMenuPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string ConsoleMenuQuit {
            get {
                return ResourceManager.GetString("ConsoleMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gespeicherte Aufträge anzeigen.
        /// </summary>
        internal static string ConsoleMenuViewJobs {
            get {
                return ResourceManager.GetString("ConsoleMenuViewJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen des Auftrags fehlgeschlagen..
        /// </summary>
        internal static string DeleteJobFailed {
            get {
                return ResourceManager.GetString("DeleteJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Auftragsnummer.
        /// </summary>
        internal static string DeleteJobInvalid {
            get {
                return ResourceManager.GetString("DeleteJobInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den zu entfernenden Auftrag ein:.
        /// </summary>
        internal static string DeleteJobPrompt {
            get {
                return ResourceManager.GetString("DeleteJobPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftrag erfolgreich entfernt.
        /// </summary>
        internal static string DeleteJobSuccess {
            get {
                return ResourceManager.GetString("DeleteJobSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zielpfad.
        /// </summary>
        internal static string DestinationPath {
            get {
                return ResourceManager.GetString("DestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Aufträge wurden erfolgreich abgeschlossen..
        /// </summary>
        internal static string ExecuteAllJobsSuccess {
            get {
                return ResourceManager.GetString("ExecuteAllJobsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausführung der Aufträge fehlgeschlagen.
        /// </summary>
        internal static string ExecuteJobsFailed {
            get {
                return ResourceManager.GetString("ExecuteJobsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Aufträge verfügbar..
        /// </summary>
        internal static string ExecuteJobsNoJobs {
            get {
                return ResourceManager.GetString("ExecuteJobsNoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine gültigen Aufträge ausgewählt..
        /// </summary>
        internal static string ExecuteJobsNoValid {
            get {
                return ResourceManager.GetString("ExecuteJobsNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie die Nummern der auszuführenden Aufträge ein (getrennt durch Kommas wie 1;3 oder 1-3):.
        /// </summary>
        internal static string ExecuteJobsPrompt {
            get {
                return ResourceManager.GetString("ExecuteJobsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufträge erfolgreich abgeschlossen..
        /// </summary>
        internal static string ExecuteJobsSuccess {
            get {
                return ResourceManager.GetString("ExecuteJobsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben die maximale Anzahl an Aufträgen erreicht. Um fortzufahren, löschen Sie bitte einen vorhandenen Auftrag. .
        /// </summary>
        internal static string MaxFileWarning {
            get {
                return ResourceManager.GetString("MaxFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Leertaste = Aktivieren/Deaktivieren, Enter = Bestätigen).
        /// </summary>
        internal static string MultipleSelectionAdvice {
            get {
                return ResourceManager.GetString("MultipleSelectionAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Hinzufügen zum Pfad.
        /// </summary>
        internal static string PathAddError {
            get {
                return ResourceManager.GetString("PathAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drücken Sie eine beliebige Taste, um fortzufahren....
        /// </summary>
        internal static string PressKeyToContinue {
            get {
                return ResourceManager.GetString("PressKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten Sie Ihr Terminal neu, damit dies wirksam wird..
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differenzielle Sicherung.
        /// </summary>
        internal static string SaveDifferentialType {
            get {
                return ResourceManager.GetString("SaveDifferentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vollständige Sicherung.
        /// </summary>
        internal static string SaveFullType {
            get {
                return ResourceManager.GetString("SaveFullType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quellpfad.
        /// </summary>
        internal static string SourcePath {
            get {
                return ResourceManager.GetString("SourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vielen Dank für die Nutzung von EasySave.
        /// </summary>
        internal static string ThankYouForUsing {
            get {
                return ResourceManager.GetString("ThankYouForUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Auftrag verfügbar..
        /// </summary>
        internal static string ViewJobsNoJob {
            get {
                return ResourceManager.GetString("ViewJobsNoJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier sind die Aufträge:.
        /// </summary>
        internal static string ViewJobsTitle {
            get {
                return ResourceManager.GetString("ViewJobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache bereits aktiv..
        /// </summary>
        internal static string WarningLanguageActive {
            get {
                return ResourceManager.GetString("WarningLanguageActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokollformat bereits aktiv..
        /// </summary>
        internal static string WarningLogFormatActive {
            get {
                return ResourceManager.GetString("WarningLogFormatActive", resourceCulture);
            }
        }
    }
}
